### ISSUE TITLE
Problems with python targets after #3

### ISSUE THREAD

**Issue by heikoengel** [erpalma/throttled-overlay#4]
I see the underlying change is addressed in #3 but I cannot update my system anymore with throttled-overlay at post-#3:

```
# emerge -avuDN --changed-deps world

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds built with USE flags to satisfy "dev-python/dbus-python[python_single_target_python3_6(-)?]".
!!! One of the following packages is required to complete your request:
- sys-power/throttled-0.6::throttled (Change USE: -python_single_target_python3_6, this change violates use flag constraints defined by sys-power/throttled-0.6: 'exactly-one-of ( python_single_target_python3_6 )')
(dependency required by "sys-power/throttled-0.6::throttled" [ebuild])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```

```
# eix dbus-python
[I] dev-python/dbus-python
     Available versions:  1.2.4^t 1.2.12^t ~1.2.14^t {doc examples test PYTHON_TARGETS="python2_7 python3_6 python3_7 python3_8"}
     Installed versions:  1.2.12^t(10:01:31 PM 02/16/2020)(-doc -examples -test PYTHON_TARGETS="python2_7 python3_6 -python3_7")
     Homepage:            https://www.freedesktop.org/wiki/Software/DBusBindings https://dbus.freedesktop.org/doc/dbus-python/
     Description:         Python bindings for the D-Bus messagebus
```

If I go back to pre-#3 / rev. 937b9ec I see that the system doesn't like the throttled ebuild (as expected) but at least allows me to update all other packages:
```
# emerge -avuDN --changed-deps world
[...]
!!! The following installed packages are masked:
- sys-power/throttled-0.6::throttled (masked by: invalid: RDEPEND: Invalid atom (Invalid use dep: '%PYTHON_USEDEP-HAS-BEEN-REMOVED%'), token 6 in '/var/db/pkg/sys-power/throttled-0.6/RDEPEND')
For more information, see the MASKED PACKAGES section in the emerge
man page or refer to the Gentoo Handbook.
```

Do you have any idea on what may be wrong with the #3 changes in my system? 
Thanks!

**edit**:
the following seems to work for me, but I'm not familiar enough with the topic to decide if this is a proper solution:
```patch
diff --git a/sys-power/throttled/throttled-0.6.ebuild b/sys-power/throttled/throttled-0.6.ebuild
index 9ae9d08..a72e16f 100644
--- a/sys-power/throttled/throttled-0.6.ebuild
+++ b/sys-power/throttled/throttled-0.6.ebuild
@@ -19,8 +19,9 @@ IUSE=""
 REQUIRED_USE=${PYTHON_REQUIRED_USE}"
 
 RDEPEND="${PYTHON_DEPS}
-       dev-python/dbus-python[${PYTHON_USEDEP}]
-       dev-python/pygobject[${PYTHON_USEDEP}]
+       $(python_gen_cond_dep '
+       dev-python/dbus-python[${PYTHON_MULTI_USEDEP}]
+       dev-python/pygobject[${PYTHON_MULTI_USEDEP}]')
 "
 DEPEND="${PYTHON_DEPS}"
 
```

**Comment by zamlz** [comment]
Can confirm that the issue also exists on my system as well.

**Comment by vowstar** [comment]
This issue also exists on my system

**Comment by baergj** [comment]
Presumably #2 fixes this (and adds multi-target support while it's at it), though the patch above is what I arrived at locally as well.

**Comment by zamlz** [comment]
I think it's because the ebuild now also supports multiple different
versions of python. Don't take my word for it though.

**Comment by imaspacepirate** [comment]
#5 should work for now. There will be problems later on. As @erpalma mentions,

> The tool is now running with Python3 by default (tested w/ 3.6) and a virtualenv is automatically created in /opt/lenovo_fix. Python2 should probably still work. 

This won't be the case for very long as Gentoo Devs have said they will be deprecating Python 2.7 support very soon (the exact details are in the related NEWS item). This may have to change back to a python-single-r1 or if ports to newer versions of Python work we may get away with a python-multi-use. The newer python-depends syntax entails that complexity will generally increase when one is handling ebuilds making use of python-multi-use. In particular, the issue that seems apparent immediately with python-multi-use over python-single-r1 is that multi-use will most likely increase the likelihood of slot conflicts depending on the dependencies other packages have to the different Python installations. Many times it is *non-trivial* to resolve these conflicts in a coherent manner. Additionally python-multi-use also requires the developer to maintain their package for multiple different versions of Python which again, depending on the software itself may be non-trivial.

Regardless, those of you using anything other than the 9999.ebuild should consider moving to the 9999.ebuild. Not only because Python 2.7 support will be sunset very soon but also because there have been commits that are not necessarily present in other ebuild versions. Indeed, looking at the activity on the [main repository](https://github.com/erpalma/throttled) more commits will most likely be on the way.

Also @erpalma, Michał Górny added links to some extra clarifications and a [repository](https://github.com/mgorny/python-guide/) with examples on [Planet Gentoo](https://planet.gentoo.org/universe/).
